graphhopper:
  datareader.file: /data/us-latest.osm.pbf
  graph.location: /data/graph-cache
  custom_models.directory: /graphhopper/custom-models
  profiles:
    - name: foot
      custom_model_files: [foot_cm.json]
    - name: trail
      custom_model_files: [trail_runner_cm.json]
  profiles_ch: []
  profiles_lm:
    - profile: foot
    - profile: trail
  graph.encoded_values: foot_access,foot_average_speed,foot_priority,road_class,road_environment,surface,average_slope
  graph.elevation.provider: srtm
  graph.elevation.cache_dir: /data/srtm-cache
  import.osm.ignored_highways: motorway,trunk
  graph.dataaccess.default_type: MMAP
  routing.non_ch.max_waypoint_distance: 1000000
server:
  application_connectors:
    - type: http
      port: 8989
      bind_host: 0.0.0.0
